# Form implementation generated from reading ui file 'ui/cargue_vehiculo.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(312, 346)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setStyleSheet("color: rgb(0, 0, 0);\n"
"border:1px solid #DBDADE;\n"
"border-radius:5px;\n"
"padding:5px 0;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.frame)
        self.radioButton_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"padding:0;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(parent=self.frame)
        self.radioButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.verticalLayout.addWidget(self.frame)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"border:1px solid #DBDADE;\n"
"border-radius:5px;\n"
"padding:5px 0;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"border:1px solid #DBDADE;\n"
"border-radius:5px;\n"
"padding:5px 0;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"border:1px solid #DBDADE;\n"
"border-radius:5px;\n"
"padding:5px 0;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setStyleSheet("background-color: rgb(94, 90, 219);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:5px;\n"
"padding:8px 0;")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cargue vehiculo"))
        self.label.setText(_translate("Form", "Placa"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Ingresa la placa del vehiculo"))
        self.label_2.setText(_translate("Form", "Tipo de vehiculo"))
        self.radioButton_2.setText(_translate("Form", "Motocicleta"))
        self.radioButton.setText(_translate("Form", "Coche"))
        self.label_4.setText(_translate("Form", "Modelo"))
        self.label_3.setText(_translate("Form", "Color"))
        self.label_5.setText(_translate("Form", "Imagen"))
        self.pushButton.setText(_translate("Form", "Cargar"))
